name: automation-runner
on:
  workflow_dispatch:
    inputs:
      runclass:
        description: 'Select class to run'
        required: true
        type: choice
        options:
          - pondsdataupdate.Bgardhdiv
          - pondsdataupdate.Gohandiv
          - pondsdataupdate.RohtakTest
          - pondsdataupdate.Sampladiv
          - wwtsupdate.Bgardhdiv
          - wwtsupdate.Gohanadiv
          - wwtsupdate.RohtakDiv
          - wwtsupdate.Sampladiv

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y tesseract-ocr tesseract-ocr-eng
          echo "TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata" >> $GITHUB_ENV

      - name: Setup Virtual Display
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1280x1024x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Build
        run: mvn clean compile        # ✅ working-directory hataya

      - name: Create creds
        run: echo '${{ secrets.GOOGLE_CREDS }}' > pondsdata-58d9eaf0ae83.json

      - name: Install Playwright
        run: mvn exec:java -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      - name: Run Selected Class
        run: mvn exec:java -Dexec.mainClass=${{ github.event.inputs.runclass }}
        env:
          TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata
          DISPLAY: :99
